name: OCI Cloud Sniper

on:
  schedule:
    - cron: '*/5 * * * *' # Runs automatically every 5 minutes
  workflow_dispatch: # Allows manually clicking the button

jobs:
  hunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, openssl

      - name: Install Oracle SDK manually
        run: |
          composer require hitrov/oci-api-php:^1.0 --no-interaction

      - name: Create Private Key File
        run: |
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ./oci_api_key.pem
          chmod 600 ./oci_api_key.pem

      - name: Execute Sniper
        env:
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          OCI_PRIVATE_KEY_FILENAME: ./oci_api_key.pem
        run: php index.php
